package Projeto_Final_POO;

public enum TipoEvento {

    DEFESA, GOL_A_FAVOR, ROUBADA_DE_BOLA, ASSISTENCIA, FINALIZACAO, FALTA_COMETIDA, CARTAO_AMARELO, CARTAP_VERMELHO,
    PASSE_CERTO, PASSE_ERRADO
}
